### ISSUE TITLE
 __vite_ssr_import_4__.default is not a function - Astro

### ISSUE THREAD

**Issue by alvarosabu** [kidonng/unocss-preset-daisy#12]
After updating to version `v2.0.0` I got this error on the console

```
08:46:44 [astro] Unable to load /Users/alvarosabu/Projects/tres-playground/astro.config.mjs

 error   __vite_ssr_import_4__.default is not a function
  File:
    /Users/alvarosabu/Projects/tres-playground/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:9
  Code:
    52419 |         const initModule = new AsyncFunction(`global`, ssrModuleExportsKey, ssrImportMetaKey, ssrImportKey, ssrDynamicImportKey, ssrExportAllKey, '"use strict";' + result.code + `\n//# sourceURL=${mod.url}`);
    > 52420 |         await initModule(context.global, ssrModule, ssrImportMeta, ssrImport, ssrDynamicImport, ssrExportAll);
            |         ^
      52421 |     }
      52422 |     catch (e) {
      52423 |         mod.ssrError = e;
  Stacktrace:
TypeError: __vite_ssr_import_4__.default is not a function
    at eval (/Users/alvarosabu/Projects/tres-playground/.temp.1677916004625.config.mjs:64:38)
    at async instantiateModule (file:///Users/alvarosabu/Projects/tres-playground/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:9)

```

package.json

```
"dependencies": {
    "@astrojs/mdx": "^0.17.2",
    "@astrojs/vue": "^2.0.1",
    "astro": "^2.0.17",
    "astro-seo": "^0.7.1",
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@kidonng/daisyui": "^2.51.3",
    "@unocss/astro": "^0.50.3",
    "@unocss/reset": "^0.50.3",
    "unocss": "^0.50.3",
    "unocss-preset-daisy": "^2.0.0",

  }
```

**Comment by kidonng** [comment]
https://github.com/kidonng/unocss-preset-daisy/issues/11#issuecomment-1453359942
